PROJECTILE_UPDATE_DELTA = 0.0166667
PROJECTILE_HEIGHT_COMPENSATION = 1.2
PROJECTILE_MAX_AGE = 20
PROJECTILE_MAX_OVERSHOOT = 1000
PROJECTILE_DEFAULT_MUZZLE_VELOCITY = 827 / 2
PROJECTILE_UI_MARK_SIZE = 10

PROJECTILE_PENETRATION_DEFAULT_MATERIAL = {
    absorb_percentage = 1,
    minimum_energy = 9999,
    chance_to_terminate = 1,
}
