---@class (exact) ProjectileAttack
---@field heading number Heading degrees [0, 360]
---@field pitch number Pitch degrees wrt XZ-plane (<=90)
---
---@class (exact) ProjectileSprite
---@field handle number LoadSprite handle
---@field width number
---@field aspect_ratio number Aspect ratio wrt sprite width
---
---@class ProjectileSoundManifest
---@field fire? number
---@field whistle? number|number[]
---
---@see MakeHole
---@class ProjectileMakeHoleSizes
---@field soft number
---@field medium? number
---@field hard? number
---
---@class ProjectileInitialValues
---@field attack ProjectileAttack
---@field deviation? number Deviate destination up to <number> metres (radius)
---@field requested_destination TVec Projectile destination before offsets are applied
---@field state? SHELL_STATE Initial shell state
---@field delay? number Accumulated delay before projectile is active
---@field timeToDestination number Time in seconds to reach destination
---
---@class ProjectileCache
---@field delay number
---@field [string] any
---
---@class ProjectilePenetration
---@field absorb_percentage? number Percentage of kinetic energy to absorb.\nEx: 0.10 -> [1000ke * (1 - 0.10) = 900ke]
---@field minimum_energy? number Minimum amount of kinetic energy for shell to continue through material
---@field chance_to_terminate? number Percentage chance for shell to terminate (i.e detonate) regardless of minimum_energy
---
---@class (exact) ProtoProjectile
---@field _initial ProjectileInitialValues
---@field _cache ProjectileCache
---@field type string
---
---@class (exact) Projectile : ProtoProjectile
---@field age number
---@field destination TVec
---@field state SHELL_STATE
---@field transform TTransform
---@field velocity TVec
---
---@class ProjectileProps
---@field munition_class string Ordnance class, calibre, or weapon system
---@field munition_type string Munition variant. Ex. "High Explosive"
---@field weight? number Projectile weight in kilograms
---@field muzzle_velocity? number Muzzle velocity or top speed during ascent in m/s
---@field sprite? ProjectileSprite
---@field sounds? ProjectileSoundManifest
---@field explosive_yield? number Size of projectile explosion if applicable [0, 4]
---@field hole_sizes? ProjectileMakeHoleSizes
---@field penetration? { [Material]: ProjectilePenetration }
---
---@class (exact) ProjectileBehaviourLifecycleFunctions
---@field afterInit? ProjectileAfterInitFn
---@field afterTick? ProjectileAfterTickFn
---@field afterUpdate? ProjectileAfterUpdateFn
---@field beforeInit? ProjectileBeforeInitFn
---@field beforeTick? ProjectileBeforeTickFn
---@field beforeUpdate? ProjectileBeforeUpdateFn
---@field onDraw? ProjectileDrawFn
---@field onInit? ProjectileInitFn
---@field onTick? ProjectileTickFn
---@field onUpdate? ProjectileUpdateFn
---
---@class (exact) ProjectileBehaviourDefinition : ProjectileBehaviourLifecycleFunctions
---@field id string Behaviour identity used for dependency resolution
---@field requires? string[] Behaviour ids that must run before this behaviour
---
---@class (exact) ProjectileDefinition : ProjectileBehaviourLifecycleFunctions
---@field props ProjectileProps

---@alias ProjectileInitFn fun(projectile: Projectile, props: ProjectileProps): boolean? Skip next?
---@alias ProjectileBeforeInitFn fun(projectile: ProtoProjectile, props: ProjectileProps): boolean? Skip next?
---@alias ProjectileAfterInitFn ProjectileInitFn
---
---@alias ProjectileTickFn fun(projectile: Projectile, props: ProjectileProps, dt: number): boolean? Skip next?
---@alias ProjectileBeforeTickFn ProjectileTickFn
---@alias ProjectileAfterTickFn ProjectileTickFn
---
---@alias ProjectileUpdateFn fun(projectile: Projectile, props: ProjectileProps, dt: number): boolean? Skip next?
---@alias ProjectileBeforeUpdateFn ProjectileUpdateFn
---@alias ProjectileAfterUpdateFn ProjectileUpdateFn
---
---@alias ProjectileDrawFn fun(projectile: Projectile, props: ProjectileProps): boolean? Skip next?
---
---@alias ProjectileHandlerKey
---| '"afterInit"'
---| '"afterTick"'
---| '"afterUpdate"'
---| '"beforeInit"'
---| '"beforeTick"'
---| '"beforeUpdate"'
---| '"onDraw"'
---| '"onInit"'
---| '"onTick"'
---| '"onUpdate"'
---
---@alias ProjectileDefinitionGenerator fun(typeName: string): ProjectileDefinition
---
---@alias ProjectileBehaviourGenerator fun(props: ProjectileProps): ProjectileBehaviourDefinition
---@alias ProjectileBehaviour ProjectileBehaviourDefinition|ProjectileBehaviourGenerator
---
---@alias Material
---| "brick"
---| "concrete"
---| "default"
---| "dirt"
---| "foliage"
---| "glass"
---| "heavymetal"
---| "masonry"
---| "metal"
---| "plaster"
---| "plastic"
---| "rock"
---| "snow"
---| "wood"
