---@class (exact) ProjectileAttack
---@field heading number Heading degrees [0, 360]
---@field pitch number Pitch degrees wrt XZ-plane (<=90)
---
---@class (exact) ProjectileSprite
---@field handle number LoadSprite handle
---@field width number
---@field aspect_ratio number Aspect ratio wrt sprite width
---
---@class ProjectileSoundManifest
---@field fire? number
---@field whistle? number
---
---@see MakeHole
---@class ProjectileMakeHoleSizes
---@field soft number
---@field medium? number
---@field hard? number
---
---@class ProjectileInitialValues
---@field attack ProjectileAttack
---@field deviation? number Deviate destination up to <number> metres (radius)
---@field requested_destination TVec Projectile destination before offsets are applied
---@field state? SHELL_STATE Initial shell state
---@field delay? number Accumulated delay before projectile is active
---@field timeToDestination number Time in seconds to reach destination
---
---@class ProjectileCache
---@field delay number
---@field [string] any
---
---@class (exact) Projectile
---@field _initial ProjectileInitialValues
---@field _cache ProjectileCache
---@field age number
---@field destination TVec
---@field state SHELL_STATE
---@field transform TTransform
---@field type string
---@field velocity TVec
---
---@class ProjectileProps
---@field muzzleVelocity? number Muzzle velocity or top speed during ascent in m/s
---@field sprite? ProjectileSprite
---@field sounds? ProjectileSoundManifest
---@field explosiveYield? number Size of projectile explosion if applicable [0, 4]
---@field makeHoleSizes? ProjectileMakeHoleSizes
---
---@class (exact) ProjectileBehaviourFuncs
---@field afterInit? ProjectileAfterInitFn
---@field afterTick? ProjectileAfterTickFn
---@field afterUpdate? ProjectileAfterUpdateFn
---@field beforeTick? ProjectileBeforeTickFn
---@field beforeUpdate? ProjectileBeforeUpdateFn
---@field onDraw? ProjectileDrawFn
---@field onInit? ProjectileInitFn
---@field onTick? ProjectileTickFn
---@field onUpdate? ProjectileUpdateFn
---
---@class (exact) ProjectileDefinition : ProjectileBehaviourFuncs
---@field props ProjectileProps

---@alias ProjectileInitFn fun(projectile: Projectile, props: ProjectileProps): boolean? Skip next?
---@alias ProjectileAfterInitFn ProjectileInitFn
---
---@alias ProjectileTickFn fun(projectile: Projectile, props: ProjectileProps, dt: number): boolean? Skip next?
---@alias ProjectileBeforeTickFn ProjectileTickFn
---@alias ProjectileAfterTickFn ProjectileTickFn
---
---@alias ProjectileUpdateFn fun(projectile: Projectile, props: ProjectileProps, dt: number): boolean? Skip next?
---@alias ProjectileBeforeUpdateFn ProjectileUpdateFn
---@alias ProjectileAfterUpdateFn ProjectileUpdateFn
---
---@alias ProjectileDrawFn fun(projectile: Projectile, props: ProjectileProps): boolean? Skip next?
---
---@alias ProjectileHandlerKey
---| '"afterInit"'
---| '"afterTick"'
---| '"afterUpdate"'
---| '"beforeTick"'
---| '"beforeUpdate"'
---| '"onDraw"'
---| '"onInit"'
---| '"onTick"'
---| '"onUpdate"'
---
---@alias ProjectileDefinitionGenerator fun(typeName: string): ProjectileDefinition
---
---@alias ProjectileBehaviourGenerator fun(props: ProjectileProps): ProjectileBehaviourFuncs
---@alias ProjectileBehaviour ProjectileBehaviourFuncs|ProjectileBehaviourGenerator
